class ListComponentsParameters {
  static final cpuList = [
    "Name",
    "Cpu producer",
    "Year of release",
    "Motherboard socket",
    "Count of cores",
    "Count of threads",
    "Base frequency",
    "Turbo frequency",
    "L3 Cache",
    "Cpu generation",
    "Technical process",
    "TDP",
    "Max temperature",
    "Embedded graphic",
    "Cpu Pcie version",
    "CPU Tech",
    "Recommended price",
    "Performance level",
    "Description",
  ];
  static final gpuList = [
    "Name",
    "Gpu producer",
    "Name",
    "Gpu vendor",
    "Year of release",
    "Technical process",
    "Gpu frequency",
    "Memory amount",
    "Gpu memory type",
    "Memory frequency",
    "Bus",
    "TDP",
    "Gpu connector",
    "Gpu interface type",
    "Length",
    "Gpu technologies",
    "Recommended price",
    "Performance level",
    "Description",
  ];
  static final motherboardList = [
    "Name",
    "Socket",
    "CPU Generations",
    "Chipset",
    "Form Factor",
    "Producer",
    "Max TDP of Processors",
    "Memory Slots",
    "Supported Memory Frequency",
    "Max Amount of RAM",
    "Network",
    "Bluetooth",
    "Wi-Fi",
    "CPU PCIe Version",
    "PCI Express x16",
    "PCI Express x4",
    "PCI Express x1",
    "SATA3",
    "M.2",
    "D-Sub",
    "DVI",
    "HDMI",
    "DisplayPort",
    "USB 2.0",
    "USB 3.0",
    "USB Type-C",
    "Digital Audio Jack",
    "Recommended Price",
    "Performance Level",
    "Description",
  ];
  static final memoryList = [
    "Name",
    "Ram producer",
    "Ram memory type",
    "Memory capacity",
    "Frequency",
    "Ram timings",
    "Power supply voltage",
    "Recommended price",
    "Performance level",
    "Description",
  ];
  static final ssdList = [
    "Name",
    "Storage producer",
    "Storage size",
    "Storage form factor",
    "Storage interface",
    "Buffer size",
    "Reading speed",
    "Writing speed",
    "SSD cells type",
    "Recommended price",
    "Performance level",
    "Description",
  ];
  static final hddList = [
    "Name",
    "Storage producer",
    "Storage size",
    "Speed",
    "Storage form factor",
    "Storage interface",
    "Buffer size",
    "Reading speed",
    "Writing speed",
    "Recommended price",
    "Performance level",
    "Description",
  ];
  static final coolerList = [
    "Name",
    "Cooler producer",
    "Cooler socket",
    "Cooler material",
    "Max TDP",
    "Thermal tubes",
    "Recommended price",
    "Performance level",
    "Description",
  ];
  static final powerSupplyList = [
    "Power supply producer",
    "Name",
    "Power",
    "Form factor",
    "Performance level",
    "PFC module",
    "Modular connection",
    "Power supply protection functions",
    "CPU 4-pin",
    "CPU 4+4-pin",
    "CPU 8-pin",
    "PCIe 6+2-pin",
    "PCIe 8-pin",
    "PCIe 5/16-pin",
    "SATA",
    "Count of 12V lines",
    "Recommended price",
    "Description",
  ];
  static final caseList = [
    "Name",
    "Case producer",
    "Case size",
    "Form factor",
    "Case power supply location",
    "Fans included",
    "USB 3.2",
    "USB 3.0",
    "USB 2.0",
    "Design features",
    "Max length of graphic card",
    "Power supply form factor",
    "Recommended price",
    "Performance level",
    "Description",
  ];
}
